name: "CI Basics"

on:
    push: ~
    workflow_dispatch: ~

jobs:
    hello:
        name: "Hello"
        runs-on: ubuntu-latest
        steps:
            - name: "Hello, World!"
              run: echo "Hello, World!"
    
    goodbye:
        name: "Goodbye"
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
           - name: "Goodbye, World!"
             run: | 
                echo "Goodbye, World!"
                echo "Goodbye, Wolrd!"
                exit 1
           - name: "Goodbye, Space!"
             run: echo "Goodbye, Space!"
        
    hello-goodbye:
        needs: ["hello", "goodbye"]
        name: "Hello, Goodbye"
        runs-on: ubuntu-latest
        steps:
            - name: "Hello, World!"
              run: echo "Hello, World!"
            - name: "Goodbye, World!"
              run: echo "Goodbye, World!"
            - name: "Goodbye, Space!"
              run: echo "Goodbye, Space!"
        



        
