name: "CI"

on:
    push:
        paths-ignore: "./ci-baiscs.yml"
    workflow_dispatch: ~

jobs:
    deps:
        name: "Install Dependencies"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - run: ls
            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.1'
                tools: composer:v2
            - name: Install Composer Dependencies
              run: composer install
              

