name: "CI"

on:
    push:
        paths-ignore: "./ci-baiscs.yml"
    workflow_dispatch: ~

jobs:
    deps:
        name: "Install Dependencies"
        runs-on: ubuntu-latest
        services:
            database:
                image: mysql
                env:
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: app_test
                    MYSQL_ROOT_HOST: "%"
                ports:
                    - 3306:3306
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - run: ls
            - name: "Setup PHP with PECL extension"
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.1'
                tools: composer:v2, php-cs-fixer
            - name: "Install Composer Dependencies"
              run: |
                export APP_ENV=test
                composer install --prefer-dist --no-interaction --no-progress
            - name: "Check DATABASE heathly"
              run: nc -vz 127.0.0.1 3306
            - name: "Run Migrations"
              run: php bin/console d:m:m
              env:
                APP_ENV: test
                DATABASE_HOST: 127.0.0.1
                DATABASE_PASSWORD: password
                DATABASE_NAME: app
            - name: "run tests unit"
              run: php bin/phpunit tests/_1_Unit
            - name: "run tests functional"
              continue-on-error: true
              run: php bin/phpunit tests/_3_Application
              env:
                APP_ENV: test
                DATABASE_HOST:  127.0.0.1
                DATABASE_PASSWORD: password
                DATABASE_NAME: app
            - name: "run phpstan"
              run: ./vendor/bin/phpstan analyse src --level=7
            - name: "run php-cs-fixer"
              run: php-cs-fixer check src --diff


